# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [ ]:
!python -V

Python 3.10.11


# 1.3 Trabalhando com arrays Numpy

In [ ]:
import numpy as np

funções da biblioteca Numpy para ler um conjunto de dados de um arquivo externo (txt) e transformar estas informações em arrays Numpy

In [ ]:
km = np.loadtxt('carros-km.txt')

In [ ]:
km

In [ ]:
anos = np.loadtxt('carros-anos.txt', dtype = int)

In [ ]:
anos

### Obtendo a quilometragem média por ano

In [ ]:
km_media = km / (2323 - anos) # se tiver divisão por zero o retorno será: nan

In [ ]:
km_media

array([1.38781250e+02, 1.72048193e+01, 1.11480480e+02, 0.00000000e+00,
       8.12523659e+01, 3.44951768e+01, 0.00000000e+00, 2.47130573e+02,
       3.16923323e+02, 1.21724359e+02, 4.00591900e+01, 2.54810127e+01,
       2.78798137e+02, 0.00000000e+00, 1.32028662e+02, 3.76570033e+02,
       1.49353698e+02, 0.00000000e+00, 1.20801303e+02, 4.95849673e+01,
       3.15242991e+02, 0.00000000e+00, 2.98112462e+02, 3.10117470e+02,
       0.00000000e+00, 0.00000000e+00, 1.88762215e+01, 0.00000000e+00,
       1.83327103e+02, 2.84280120e+02, 9.25245399e+01, 1.62597561e+02,
       5.80983607e+01, 1.01831325e+02, 2.93475728e+02, 1.34070122e+02,
       0.00000000e+00, 0.00000000e+00, 1.75987261e+01, 0.00000000e+00,
       3.01338710e+02, 1.27381250e+02, 0.00000000e+00, 2.68853583e+02,
       0.00000000e+00, 3.03894081e+01, 2.19263323e+02, 7.43788820e+00,
       0.00000000e+00, 2.51090625e+02, 2.72464968e+02, 1.59293375e+02,
       2.09647059e+02, 2.96362776e+02, 1.12923323e+02, 2.46221884e+02,
      

In [ ]:
type(km_media)

numpy.ndarray

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [ ]:
2+2

4

### Subtração ($-$)

In [ ]:
2-2

0

### Multiplicação ($*$)

In [ ]:
2*2

4

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [ ]:
10/3

3.3333333333333335

In [ ]:
10//3

3

### Exponenciação ($**$)

In [ ]:
2**3

8

### Resto da divisão ($\%$)

In [ ]:
10%2

0

In [ ]:
10%3

1

### Expressões matemáticas

In [ ]:
5*2+3*2

16

In [ ]:
3*2+5*2

16

In [ ]:
3*(2+5)*2

42

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [ ]:
5*2

10

In [ ]:
_ +3*6

28

In [ ]:
_ / 2

14.0

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [ ]:
ano_atual = 2023
ano_fabricacao = 2003
km_total = 44410.0

In [ ]:
ano_atual

2023

In [ ]:
ano_fabricacao

2003

In [ ]:
km_total

44410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [ ]:
km_media = km_total/(ano_atual-ano_fabricacao)
km_media

2220.5

In [ ]:
ano_atual = 2023
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total/(ano_atual-ano_fabricacao)
km_media

2220.5

In [ ]:
ano_atual = 2023
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total/(ano_atual-ano_fabricacao)

km_total = km_total + km_media
km_total

46630.5

In [ ]:
ano_atual = 2023
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total/(ano_atual-ano_fabricacao)

km_total += km_media
km_total

46630.5

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [ ]:
ano_atual, ano_fabricacao, km_total = 2023, 2003, 44410.0

In [ ]:
ano_atual

2023

In [ ]:
ano_fabricacao

2003

In [ ]:
km_total

44410.0

In [ ]:
ano_atual, ano_fabricacao, km_total = 2023, 2003, 44410.0
km_media = km_total/(ano_atual-ano_fabricacao)
km_media

2220.5

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [ ]:
ano_atual = 2023

In [ ]:
type(ano_atual)

int

In [ ]:
km_total = 44410.0

In [ ]:
type(km_total)

float

### Booleanos

In [ ]:
zero_km = True

In [ ]:
type(zero_km)

bool

In [ ]:
zero_km = False

In [ ]:
type(zero_km)

bool

### Strings

In [ ]:
nome = 'Jetta Variant'
nome

'Jetta Variant'

In [ ]:
nome = "Jetta Variant"
nome

'Jetta Variant'

In [ ]:
nome = 'Jetta "Variant"'
nome

'Jetta "Variant"'

In [ ]:
nome = "Jetta 'Variant'"
nome

"Jetta 'Variant'"

In [ ]:
carro = '''
  Nome
  Idade
  Nota
'''
carro

'\n  Nome\n  Idade\n  Nota\n'

In [ ]:
type(carro)

str

### None

In [ ]:
quilometragem = None
quilometragem

In [ ]:
type(quilometragem)

NoneType

# 2.4 Conversão de tipos

In [ ]:
a, b, c, d = 10, 20, 'Python é ', 'legal'

In [ ]:
type(a)

int

In [ ]:
type(b)

int

In [ ]:
type(c)

str

In [ ]:
type(d)

str

In [ ]:
a+b

30

In [ ]:
c+d

'Python é legal'

In [ ]:
c+a

### Conversões de tipo

Funções int(), float(), str()

In [ ]:
str(a)

'10'

In [ ]:
type(str(a))

str

In [ ]:
c+str(a)

'Python é 10'

In [ ]:
float(a)

10.0

In [ ]:
var = 3.141592

In [ ]:
type(var)

float

In [ ]:
new_var = int(var)

In [ ]:
type(new_var)

int

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [ ]:
ano_atual = 2023
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Falso


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [ ]:
# Isto é um comentário
ano_atual = 2019
ano_atual

In [ ]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

In [ ]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

In [ ]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Verdadeiro


### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [ ]:
print('Olá, {}!'.format('Michel'))

Olá, Michel!


In [ ]:
print('Olá, {}! Este é seu acesso de número {}'.format('Michel', 32))

Olá, Michel! Este é seu acesso de número 32


In [ ]:
print('Olá, {nome}! Este é seu acesso de número {acessos}'.format(nome='Michel', acessos=32))


Olá, Michel! Este é seu acesso de número 32


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [ ]:
nome = 'Michel'
acessos = 32

In [ ]:
print(f'Olá, {nome}! Este é seu acesso de número {acessos}')


Olá, Michel! Este é seu acesso de número 32


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [ ]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
type(Acessorios)

list

### Lista com tipos de dados variados

In [ ]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [ ]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [ ]:
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [ ]:
carros = [Carro_1, Carro_2]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
'Rodas de liga' in Acessorios

True

In [ ]:
'4x4' in Acessorios

False

In [ ]:
'4x4' not in Acessorios

True

In [ ]:
'Rodas de liga' not in Acessorios

False

## *A + B*

Concatena as listas *A* e *B*.

In [ ]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [ ]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [ ]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
A+B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [ ]:
len(Acessorios)

8

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios[0]

'Rodas de liga'

In [ ]:
Acessorios[1]

'Travas elétricas'

In [ ]:
Acessorios[-1]

'Sensor de chuva'

In [ ]:
Acessorios[-2]

'Sensor crepuscular'

In [ ]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [ ]:
carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [ ]:
carros[0][0]

'Jetta Variant'

In [ ]:
carros[0][-2][1]

'Travas elétricas'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios[2:6] # índice 6 não entra

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento']

In [ ]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios[:5]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios.sort() #modifica a lista

In [ ]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
Acessorios = ['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
sorted(Acessorios) #nao modifica a lista

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [ ]:
Acessorios.append('4 X 4')
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 '4 X 4']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [ ]:
Acessorios.pop()

'4 X 4'

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios.pop(5)

'Sensor de estacionamento'

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [ ]:
Acessorios_2 = Acessorios
Acessorios_2

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios_2.append('4x4')
Acessorios_2

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva',
 '4x4']

In [ ]:
Acessorios #como a referência é a mesma o 4x4 vem pra cá tbm

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva',
 '4x4']

In [ ]:
Acessorios.pop()
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios_2 = Acessorios.copy() #aponta para outro lugar na memória
Acessorios_2

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios_2.append('4x4')
Acessorios_2

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva',
 '4x4']

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios_3 = Acessorios[:]
Acessorios_3

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios_3.append('4x4')
Acessorios_3

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva',
 '4x4']

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor crepuscular',
 'Sensor de chuva']

**Acessorios[:]** é equivalente a **Acessorios.copy()**

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [ ]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios2 = [('Rodas de liga', 0), ('Travas elétricas', 1), ('Piloto automático', 2), ('Bancos de couro', 3), ('Ar condicionado', 4), ('Sensor de estacionamento', 5), ('Sensor crepuscular', 6), ('Sensor de chuva', 7)]
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
for item, position in Acessorios2:
  print(item,'-',position)

Rodas de liga - 0
Travas elétricas - 1
Piloto automático - 2
Bancos de couro - 3
Ar condicionado - 4
Sensor de estacionamento - 5
Sensor crepuscular - 6
Sensor de chuva - 7


In [ ]:
for position, item in enumerate(Acessorios):
  print(item,'-',position)

Rodas de liga - 0
Travas elétricas - 1
Piloto automático - 2
Bancos de couro - 3
Ar condicionado - 4
Sensor de estacionamento - 5
Sensor crepuscular - 6
Sensor de chuva - 7


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(10):
  if i < 9:
    print(i**2, end=', ')
  else:
    print(i**2, end='. ')

0, 1, 4, 9, 16, 25, 36, 49, 64, 81. 

In [ ]:
quadrado = []
for i in range(10):
  quadrado.append(i**2)
quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
# list comprehension
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
# retorna um objeto da classe generator, que "gera" os valores sob demanda.
list_gener = (x for x in range(10))
print(list_gener)

print(f'primeiro:\n{next(list_gener)}')
print(f'segundo:\n{next(list_gener)}')

print('o resto:')
for i in list_gener:
  print(i)

<generator object <genexpr> at 0x7ff9122ec820>
primeiro:
0
segundo:
1
o resto:
2
3
4
5
6
7
8
9


In [ ]:
def even_items(iterable):
  return [v for i, v in enumerate(iterable, start=1) if not i % 2]

def alphabet():
  alpha = "abcdefghijklmnopqrstuvwxyz"
  for a in alpha:
    yield a

# alphabet[1::2]
# list(alphabet[1::2])
even_items(alphabet())

['b', 'd', 'f', 'h', 'j', 'l', 'n', 'p', 'r', 't', 'v', 'x', 'z']

In [ ]:
def other_math(number):
  print('do the math with:', number)
  
def gen_squares_in_interval(x, y):
  for i in range(x, y):
    yield i*i

x, y = (10, 20)
  
for number in gen_squares_in_interval(x, y):
  other_math(number)

do the math with: 100
do the math with: 121
do the math with: 144
do the math with: 169
do the math with: 196
do the math with: 225
do the math with: 256
do the math with: 289
do the math with: 324
do the math with: 361


In [ ]:
from sys import getsizeof

one_million = 10**6

list_compr = [x for x in range(one_million)]
# Essa função retorna o tamanho em bytes gastos pelo objeto passado por parâmetro.
print(getsizeof(list_compr))

list_gener = (x for x in range(one_million))
print(getsizeof(list_gener))

8448728
104


In [ ]:

from sys import getsizeof

def generator_split(x, chuck_size):
  for i in range(0, len(x), chuck_size):
    yield x[i:i+chuck_size]

def process_chunk(chunk):
  pass

def save_processed(processed):
  pass

if __name__ == '__main__':
  one_million = 10**6
  x = [x for x in range(one_million)]
  gen = generator_split(x, 100)

  for chunk in gen:
    print(chunk)
    processed = process_chunk(chunk)
    save_processed(processed)

In [ ]:
def fib():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b

fib_gen = fib()
print(next(fib_gen))
print(next(fib_gen))
print(next(fib_gen))
print(next(fib_gen))


0
1
1
2


# 4.2 Loops aninhados

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
for i in dados:
  print(i)
  for j in i:
    print(j)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [ ]:
Acessorios = []
for lista in dados:
  for item in lista:
    Acessorios.append(item)
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [ ]:
set(Acessorios) # assim removemos as duplicatas

{'4 X 4',
 'Ar condicionado',
 'Bancos de couro',
 'Central multimídia',
 'Controle de estabilidade',
 'Câmbio automático',
 'Câmera de estacionamento',
 'Freios ABS',
 'Painel digital',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Teto panorâmico',
 'Travas elétricas',
 'Vidros elétricos'}

In [ ]:
list(set(Acessorios))

### List comprehensions

In [ ]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [ ]:
list(set([item for lista in dados for item in lista]))

['Travas elétricas',
 '4 X 4',
 'Câmbio automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de chuva',
 'Controle de estabilidade',
 'Vidros elétricos',
 'Sensor crepuscular',
 'Painel digital',
 'Câmera de estacionamento',
 'Rodas de liga',
 'Freios ABS',
 'Piloto automático',
 'Central multimídia',
 'Sensor de estacionamento',
 'Teto panorâmico']

In [ ]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

result = []
for lista in dados:
    for item in lista:
        result.append(item)
print(result)

result_2 = []
for lista in dados:
    result_2 += lista
print(result_2)

print([item for lista in dados for item in lista])

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']


### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [ ]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
for lista in dados:
  if lista[2] == True:
    print(lista)

['DS5', 2019, True]
['A5', 2019, True]


In [ ]:
zero_km_Y = []
for lista in dados:
  if lista[2] == True:
    zero_km_Y.append(lista)
zero_km_Y

[['DS5', 2019, True], ['A5', 2019, True]]

### List comprehensions

In [ ]:
zero_km_Y = [lista for lista in dados if lista[2]==True]
zero_km_Y

In [ ]:
zero_km_N = [lista for lista in dados if lista[2]==False]
zero_km_N

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [ ]:
zero_km_Y,zero_km_N = [],[]
for lista in dados:
  if lista[2] == True:
    zero_km_Y.append(lista)
  else:
    zero_km_N.append(lista)

print(zero_km_Y)
print(zero_km_N)

[['DS5', 2019, True], ['A5', 2019, True]]
[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


In [ ]:
zero_km_Y, zero_km_N = [lista for lista in dados if lista[2] == True], [lista for lista in dados if lista[2] == False]
print(zero_km_Y)
print(zero_km_N)

[['DS5', 2019, True], ['A5', 2019, True]]
[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


In [ ]:
['par' if i % 2 == 0 else 'ímpar' for i in range(10)]

['par',
 'ímpar',
 'par',
 'ímpar',
 'par',
 'ímpar',
 'par',
 'ímpar',
 'par',
 'ímpar']

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [ ]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [ ]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [ ]:
A,B,C=[],[],[]
for lista in dados:
  if(lista[1]<=2000):
    A.append(lista)
  elif(2000 < lista[1] <= 2010):
    B.append(lista)
  else:
    C.append(lista)
print(A)
print(B)
print(C)

[['Passat', 1991, False], ['Crossfox', 1990, False]]
[['Jetta Variant', 2003, False], ['Aston Martin DB4', 2006, False], ['Série 3 Cabrio', 2009, False]]
[['DS5', 2019, True], ['Palio Weekend', 2012, False], ['A5', 2019, True], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [ ]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [ ]:
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [5]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [ ]:
km = np.array([1000,2300,4987,1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [ ]:
km.dtype

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [126]:
km = np.loadtxt(fname = 'data/carros-km.txt', dtype = int)

In [127]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [122]:
km.dtype

dtype('int64')

### Arrays com duas dimensões

In [128]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [129]:
Acessorios = np.array(dados)

In [130]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [131]:
km.shape

(258,)

In [132]:
Acessorios.shape # 3 linhas e 8 colunas

(3, 8)

### Comparando desempenho com listas

In [3]:
one_million = 10**6

In [6]:
np_array = np.arange(one_million)

In [8]:
py_list = list(range(one_million))

In [9]:
%time for _ in range(100): np_array *= 2

CPU times: user 57.3 ms, sys: 522 µs, total: 57.8 ms
Wall time: 61.1 ms


In [10]:
%time for _ in range(100): py_list = [x*2 for x in py_list]

CPU times: user 9.9 s, sys: 5.58 s, total: 15.5 s
Wall time: 15.9 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [11]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [18]:
idade = 2023 - anos #dá erro

In [19]:
idade = [2023-ano for ano in anos]
idade

[20, 32, 33, 4, 17]

In [23]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [31]:
idade = 2023 - anos

In [32]:
idade

array([20, 32, 33,  4, 17])

### Operações entre arrays

In [26]:
km_media = km / idade

In [33]:
km_media

array([2220.5       ,  178.5       , 1124.93939394,    0.        ,
       1515.11764706])

In [37]:
0/(2023-1991)

0.0

### Operações com arrays de duas dimensões

In [38]:
dados = np.array([km, anos])

In [39]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [43]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [45]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [46]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [48]:
km_media = dados[0]/(2023-dados[1])
km_media

array([2220.5       ,  178.5       , 1124.93939394,    0.        ,
       1515.11764706])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [49]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [51]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
contador[0]

0

In [53]:
item=6
index = item -1
contador[index]

5

In [54]:
contador[-1]

9

In [56]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [57]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [59]:
dados[1][2]

1990.0

In [58]:
dados[1,2]

1990.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [61]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
contador[1:4]

array([1, 2, 3])

In [63]:
contador[1:8:2]


array([1, 3, 5, 7])

In [66]:
contador[::2] #pega pares


array([0, 2, 4, 6, 8])

In [67]:
contador[1::2] #pega ímpares


array([1, 3, 5, 7, 9])

In [60]:
contador[::-1] #inverte

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [68]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [75]:
dados[:,1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [80]:
dados[:,1:3][0]/(2023 - dados[:,1:3][1])

array([ 178.5       , 1124.93939394])

In [85]:
dados[0][1:3] / (2023-dados[1][1:3])

array([ 178.5       , 1124.93939394])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [86]:
ador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [88]:
contador[contador > 5]


array([6, 7, 8, 9])

In [89]:
contador[[False, False, False, False, False, False,  True,  True,  True,
        True]]

array([6, 7, 8, 9])

In [92]:
dados[1]>2000

array([ True, False, False,  True,  True])

In [93]:
dados[:,dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [96]:
dados[:,dados[1]>2000][0]/(2023 - dados[:,dados[1]>2000][1])

array([2220.5       ,    0.        , 1515.11764706])

In [104]:
exerc = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteira', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casada', 'feminino']
    ]
)

In [107]:
exerc[:,:2]

array([['Roberto', 'casado'],
       ['Sheila', 'solteira'],
       ['Bruno', 'solteiro'],
       ['Rita', 'casada']], dtype='<U9')

In [108]:
exerc[:,2:]


array([['masculino'],
       ['feminino'],
       ['masculino'],
       ['feminino']], dtype='<U9')

In [112]:
exerc[:2,:2]


array([['Roberto', 'casado'],
       ['Sheila', 'solteira']], dtype='<U9')

In [118]:
exerc

array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'solteira', 'feminino'],
       ['Bruno', 'solteiro', 'masculino'],
       ['Rita', 'casada', 'feminino']], dtype='<U9')

In [129]:
exerc[::]


array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'solteira', 'feminino'],
       ['Bruno', 'solteiro', 'masculino'],
       ['Rita', 'casada', 'feminino']], dtype='<U9')

In [132]:
exerc[::1]


array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'solteira', 'feminino'],
       ['Bruno', 'solteiro', 'masculino'],
       ['Rita', 'casada', 'feminino']], dtype='<U9')

In [142]:
exerc[::2]

array([['Rita', 'casada', 'feminino'],
       ['Sheila', 'solteira', 'feminino']], dtype='<U9')

In [144]:
exerc[::3]

array([['Roberto', 'casado', 'masculino'],
       ['Rita', 'casada', 'feminino']], dtype='<U9')

In [135]:
exerc[::4]

array([['Roberto', 'casado', 'masculino']], dtype='<U9')

In [117]:
exerc[0::2, :2]


array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

In [141]:
exerc[::-2,:2]


array([['Rita', 'casada'],
       ['Sheila', 'solteira']], dtype='<U9')

# 5.4 Atributos e métodos de arrays Numpy

In [145]:
import numpy as np

In [146]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

dados = np.array([km, anos])

In [147]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [148]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [149]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [150]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [152]:
dados.dtype # lembre-se: aqui só posso ter um tipo de dado, diferente das listas que podem ter vários tipos.

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [155]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [153]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [154]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [156]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [157]:
list(dados) # veja a diferença

[array([44410.,  5712., 37123.,     0., 25757.]),
 array([2003., 1991., 1990., 2019., 2006.])]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [158]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [161]:
contador.reshape((5,2), order='C') # padrão: C. usa a indexação da linguagem C

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [162]:
contador.reshape((5,2), order='F') # usa a indexação da linguagem fortran

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [164]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [165]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [167]:
np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [169]:
np.array(info_carros).reshape((5,2), order='F')


array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [172]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [174]:
dados_new.resize((3,5), refcheck=False)

In [175]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [176]:
dados_new[2] = dados_new[0] / (2023 - dados_new[1])

In [177]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2220.5       ,   178.5       ,  1124.93939394,     0.        ,
         1515.11764706]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [181]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [183]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [ ]:
dataset = np.column_stack((anos, km, valor))
dataset

In [187]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [189]:
np.mean(dataset) # faz a média juntando tudo

48489.14648578811

In [190]:
np.mean(dataset, axis = 0) # faz a média juntando os elementos de cada coluna

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis = 1) # faz a média juntando os elementos de cada linha


In [193]:
np.mean(dataset[:,1], axis = 0) # média dos km's

44499.41472868217

In [194]:
np.mean(dataset[:,2]) # média dos valores dos carros

98960.51310077519

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [196]:
np.std(dataset[:,2]) # calculando o desvio padrão dos valores dos carros

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [199]:
dataset.sum()

37530599.379999995

In [198]:
dataset[:,].sum()

37530599.379999995

In [200]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [202]:
dataset[:, 1].sum()

11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [204]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [206]:
np.sum(dataset[:, 1])

11480849.0

In [205]:
np.sum(dataset[:, 2])

25531812.38